### ISSUE TITLE
DoS on guard-service

### ISSUE THREAD

**Issue by rhuss** [knative-extensions/security-guard#225]
with a simple loop that curls with random URL, `guard-service` fails to update the `Guardian` CR because of size limitations:

Script:

```
/ # while true
> do
> i=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 50 | head -n 1)
> curl http://helloworld-go.default/$i?$i
> done
```

results after ~ 10-20 seconds in the following logoutput:

```
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
knative-serving guard-service-6cb5b4bc6-g5h8d guard-service info	Failed to update KubeApi with new config default.helloworld-go: set crd ns default sid helloworld-go: updating resource Request entity too large: limit is 3145728
....
```

This happens with security-guard 0.4

**Comment by davidhadas** [comment]
Interesting. 
I wonder what exploded... which field do the code fail to protect the size...

Can you do a `kubectl get guardians.guard.security.knative.dev helloworld-go -o yaml` and see which parameters is exploding?

I am struggling to get this script running on macos (getting `tr: Illegal byte sequence`)

**Comment by rhuss** [comment]
> I am struggling to get this script running on macos (getting tr: Illegal byte sequence)

I'm just running it from inside the cluster via `kubectl run curl -itq --rm --image=k8spatterns/curl-jq --command -- sh`

**Comment by rhuss** [comment]
It's the `vals:` field that appends a new entry for every random number, like in:

```
     ....
     qs:
       kv:
         vals:
              00BBd0wkzq0OYL64pL76:
                digits: 0
                flags: 0
                letters: 0
                nonreadables: 0
                schars: 0
                sequences: 0
                spaces: 0
                unicodeFlags: null
                unicodes: 0
              00EI8y77Jf30W4gkJNTW:
                digits: 0
                flags: 0
                letters: 0
                nonreadables: 0
                schars: 0
                sequences: 0
                spaces: 0
                unicodeFlags: null
                unicodes: 0
              00TqarsD88lk0XTrTe4r:
                digits: 0
                flags: 0
```
